name: "Bind DNS Server"
version: "9.18-5"
slug: "bind"
description: "ISC Bind"
url: "https://github.com/cmsj/addon-bind"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  53/udp: 53
  53/tcp: 53
map:
  - config:rw
image: ghcr.io/cmsj/{arch}-addon-bind
