name: "Bind DNS Server"
version: "20231215050553"
slug: "bind"
description: "A fully featured DNS server"
url: "https://github.com/cmsj/addon-bind"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  53/udp: 53
  53/tcp: 53
map:
  - config:rw
image: ghcr.io/cmsj/{arch}-addon-bind
codenotary: cmsj@tenshu.net
backup_exclude:
  - '*/data/cache/*'
