name: Sync with upstream (initial merge)

on:
  workflow_dispatch:    # spustíš ručně přes GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/cmsj/addon-bind
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit

      - name: Push merged changes
        run: |
          git push origin main
